/*
* generated by Xtext
*/
package org.project.droolsDSL;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DdslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.project.droolsDSL.ui.internal.DdslActivator.getInstance().getInjector("org.project.droolsDSL.Ddsl");
	}
	
}
