/**
 * generated by Xtext
 */
package org.project.droolsDSL.scoping;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.project.droolsDSL.ddsl.Event;
import org.project.droolsDSL.ddsl.EventFeature;
import org.project.droolsDSL.ddsl.Statement;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class DdslScopeProvider extends AbstractDeclarativeScopeProvider {
  public IScope scope_ReferenceType_name(final Statement stateContext, final EReference ref) {
    Event _event = stateContext.getEvent();
    EList<EventFeature> _param = _event.getParam();
    IScope _scopeFor = Scopes.scopeFor(_param);
    return _scopeFor;
  }
}
