/**
 * generated by Xtext
 */
package org.project.droolsDSL.ui.contentassist;

import org.project.droolsDSL.ui.contentassist.AbstractDdslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DdslProposalProvider extends AbstractDdslProposalProvider {
}
