/*
 * generated by Xtext
 */
package org.project.droolsDSL.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DdslUiModule extends org.project.droolsDSL.ui.AbstractDdslUiModule {
	public DdslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
