/*
 * generated by Xtext
 */
package org.project.droolsDSL;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DdslRuntimeModule extends org.project.droolsDSL.AbstractDdslRuntimeModule {

}
