/**
 * generated by Xtext
 */
package org.project.droolsDSL.ui.quickfix;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.model.edit.ISemanticModification;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import org.project.droolsDSL.ddsl.EventFeature;
import org.project.droolsDSL.validation.DdslValidator;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class DdslQuickfixProvider extends DefaultQuickfixProvider {
  @Fix(DdslValidator.EVENT_LOWERCASE)
  public void capitalizeEventName(final Issue issue, final IssueResolutionAcceptor acceptor) {
    String[] _data = issue.getData();
    String _get = _data[0];
    String _plus = ("Capitalize the name of \'" + _get);
    String _plus_1 = (_plus + "\'");
    final IModification _function = new IModification() {
      public void apply(final IModificationContext context) throws Exception {
        final IXtextDocument xtextDocument = context.getXtextDocument();
        Integer _offset = issue.getOffset();
        final String firstLetter = xtextDocument.get((_offset).intValue(), 1);
        Integer _offset_1 = issue.getOffset();
        String _firstUpper = StringExtensions.toFirstUpper(firstLetter);
        xtextDocument.replace((_offset_1).intValue(), 1, _firstUpper);
      }
    };
    acceptor.accept(issue, "Capitalize event name", _plus_1, 
      "", _function);
  }
  
  @Fix(DdslValidator.FLUENT_LOWERCASE)
  public void capitalizeFluentName(final Issue issue, final IssueResolutionAcceptor acceptor) {
    String[] _data = issue.getData();
    String _get = _data[0];
    String _plus = ("Capitalize the name of \'" + _get);
    String _plus_1 = (_plus + "\'");
    final IModification _function = new IModification() {
      public void apply(final IModificationContext context) throws Exception {
        final IXtextDocument xtextDocument = context.getXtextDocument();
        Integer _offset = issue.getOffset();
        final String firstLetter = xtextDocument.get((_offset).intValue(), 1);
        Integer _offset_1 = issue.getOffset();
        String _firstUpper = StringExtensions.toFirstUpper(firstLetter);
        xtextDocument.replace((_offset_1).intValue(), 1, _firstUpper);
      }
    };
    acceptor.accept(issue, "Capitalize fluent name", _plus_1, 
      "", _function);
  }
  
  @Fix(DdslValidator.PARAM_UPPERCASE)
  public void uncapitalizeParamtName(final Issue issue, final IssueResolutionAcceptor acceptor) {
    String[] _data = issue.getData();
    String _get = _data[0];
    String _plus = ("Uncapitalize the name of \'" + _get);
    String _plus_1 = (_plus + "\'");
    final ISemanticModification _function = new ISemanticModification() {
      public void apply(final EObject element, final IModificationContext context) throws Exception {
        String[] _data = issue.getData();
        String _get = _data[0];
        String _firstLower = StringExtensions.toFirstLower(_get);
        ((EventFeature) element).setName(_firstLower);
      }
    };
    acceptor.accept(issue, "Uncapitalize event feature name", _plus_1, 
      "", _function);
  }
}
