/*
* generated by Xtext
*/
package org.project.droolsDSL.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.project.droolsDSL.services.DdslGrammarAccess;

public class DdslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DdslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.project.droolsDSL.parser.antlr.internal.InternalDdslParser createParser(XtextTokenStream stream) {
		return new org.project.droolsDSL.parser.antlr.internal.InternalDdslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DroolsModel";
	}
	
	public DdslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DdslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
